name: Daily Shopify Data Extractor

on:
  schedule:
    - cron: '10 12 * * *'  # Runs at 12 PM UTC daily
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run the Shopify data script
      run: python Addition.py
